- name: unregister systems
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if host is available
      wait_for_connection:
        timeout: 1
      register: waiting
      ignore_errors: true

    - block:
        - name: fetch facts
          action: setup

        - name: do unregistration
          include_role:
            name: oasis_roles.rhsm
          when: ansible_distribution == 'RedHat'
      when: waiting is success
  vars:
    rhsm_unregister: true
