dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: cockpit_install
    groups:
      - cockpit_install
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: testinfra
  options:
    v: true
    junit-xml: junit.xml
  lint:
    name: flake8
